-- Darwin Life Hub automation support.
-- Run this in Supabase SQL Editor before enabling cron jobs.

alter table public.news add column if not exists source_url text;
alter table public.news add column if not exists source_hash text;
alter table public.news add column if not exists ai_generated boolean not null default false;

alter table public.jobs_posts add column if not exists source_url text;
alter table public.jobs_posts add column if not exists source_hash text;
alter table public.jobs_posts add column if not exists ai_generated boolean not null default false;

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  description text,
  event_date date,
  starts_at timestamptz,
  location text,
  price text,
  price_label text,
  category text,
  tags text,
  source_url text,
  source_hash text,
  image_url text,
  ai_generated boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.events add column if not exists source_url text;
alter table public.events add column if not exists source_hash text;
alter table public.events add column if not exists ai_generated boolean not null default false;

alter table public.events enable row level security;

drop policy if exists "Events are readable by everyone" on public.events;
create policy "Events are readable by everyone"
on public.events for select
using (true);

create table if not exists public.auto_posts (
  id bigint generated by default as identity primary key,
  type text not null,
  source_url text not null,
  source_hash text not null,
  source_title text,
  target_table text,
  target_id text,
  posted_at timestamptz not null default now(),
  unique(type, source_hash)
);

create table if not exists public.auto_run_logs (
  id bigint generated by default as identity primary key,
  type text not null,
  status text not null,
  message text,
  meta jsonb,
  created_at timestamptz not null default now()
);

alter table public.auto_posts enable row level security;
alter table public.auto_run_logs enable row level security;

-- These automation tables are intended for service-role server code.
-- No public browser policies are added.
create index if not exists idx_news_source_hash on public.news(source_hash);
create index if not exists idx_jobs_source_hash on public.jobs_posts(source_hash);
create index if not exists idx_events_source_hash on public.events(source_hash);
create index if not exists idx_events_event_date on public.events(event_date);
create index if not exists idx_auto_posts_type_hash on public.auto_posts(type, source_hash);
create index if not exists idx_auto_run_logs_created on public.auto_run_logs(created_at desc);
