-- Darwin Life Hub user system support tables and policies.
-- Run this in Supabase SQL Editor once, then refresh the site.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  nickname text,
  age integer check (age is null or (age >= 13 and age <= 120)),
  gender text check (gender is null or gender in ('private', 'female', 'male', 'other')),
  avatar_url text,
  bio text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists nickname text;
alter table public.profiles add column if not exists age integer;
alter table public.profiles add column if not exists gender text;
alter table public.profiles add column if not exists avatar_url text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_age_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_age_check
      check (age is null or (age >= 13 and age <= 120));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_gender_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_gender_check
      check (gender is null or gender in ('private', 'female', 'male', 'other'));
  end if;
end $$;

alter table public.profiles enable row level security;

drop policy if exists "Profiles are readable by everyone" on public.profiles;
create policy "Profiles are readable by everyone"
on public.profiles for select
using (true);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

create table if not exists public.user_messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references auth.users(id) on delete cascade,
  receiver_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (length(trim(content)) > 0),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.user_messages enable row level security;

drop policy if exists "Users can read their messages" on public.user_messages;
create policy "Users can read their messages"
on public.user_messages for select
using (auth.uid() = sender_id or auth.uid() = receiver_id);

drop policy if exists "Users can send messages" on public.user_messages;
create policy "Users can send messages"
on public.user_messages for insert
with check (auth.uid() = sender_id);

drop policy if exists "Users can update messages they received" on public.user_messages;
create policy "Users can update messages they received"
on public.user_messages for update
using (auth.uid() = receiver_id)
with check (auth.uid() = receiver_id);

drop policy if exists "Users can delete their messages" on public.user_messages;
create policy "Users can delete their messages"
on public.user_messages for delete
using (auth.uid() = sender_id or auth.uid() = receiver_id);

create index if not exists idx_profiles_nickname on public.profiles(nickname);
create index if not exists idx_user_messages_receiver on public.user_messages(receiver_id, created_at desc);
create index if not exists idx_user_messages_sender on public.user_messages(sender_id, created_at desc);
