-- Darwin Life Hub news comments.
-- Run this in Supabase SQL Editor if users cannot comment on news.

create table if not exists public.news_comments (
  id bigint generated by default as identity primary key,
  news_id text not null,
  content text not null check (length(trim(content)) > 0),
  name text not null default '匿名',
  created_at timestamptz not null default now()
);

alter table public.news_comments add column if not exists news_id text;
alter table public.news_comments add column if not exists content text;
alter table public.news_comments add column if not exists name text not null default '匿名';
alter table public.news_comments add column if not exists created_at timestamptz not null default now();

alter table public.news_comments enable row level security;

drop policy if exists "News comments are readable by everyone" on public.news_comments;
create policy "News comments are readable by everyone"
on public.news_comments for select
using (true);

drop policy if exists "Anyone can add news comments" on public.news_comments;
create policy "Anyone can add news comments"
on public.news_comments for insert
with check (length(trim(content)) > 0);

create index if not exists idx_news_comments_news_id_created
on public.news_comments(news_id, created_at);
