-- Optional events table for Darwin Life Hub.
-- Run this in Supabase SQL Editor when you are ready to manage real events.

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  summary text,
  description text,
  event_date date,
  starts_at timestamptz,
  location text,
  price text,
  price_label text,
  category text,
  tags text,
  source_url text,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.events enable row level security;

drop policy if exists "Events are readable by everyone" on public.events;
create policy "Events are readable by everyone"
on public.events for select
using (true);

-- Inserts/updates should be done from admin tools or server-side automation
-- using SUPABASE_SERVICE_ROLE_KEY, not from public browser code.
create index if not exists idx_events_event_date on public.events(event_date);
create index if not exists idx_events_category on public.events(category);
